//
//  DataPlant.swift
//  TanamanObat
//
//  Created by mac on 30/04/20.
//  Copyright © 2020 zidniryi. All rights reserved.
//
import UIKit

var plant: [Plant] = [
    Plant(image: UIImage(named: "bawang")!, name: "Bawang Merah", kingdom: "Plantae", division:  "Magnoliophyta", description: "Bawang merah (Allium cepa L. var. aggregatum) adalah salah satu bumbu masak utama dunia yang berasal dari Iran, Pakistan, dan pegunungan-pegunungan di sebelah utaranya, tetapi kemudian menyebar ke berbagai penjuru dunia, baik sub-tropis maupun tropis. Wujudnya berupa umbi yang dapat dimakan mentah, untuk bumbu masak, acar, obat tradisional, kulit umbinya dapat dijadikan zat pewarna dan daunnya dapat pula digunakan untuk campuran sayur.", benefit: "Memperbaiki sistem pencernaan, Mengatur gula darah, Kepadatan tulang, Menurunkan risiko kanker"),
    Plant(image: UIImage(named: "lidah_buaya")!, name: "Lidah Buaya", kingdom: "Plantae", division:  "Tracheophyta", description: "Lidah buaya (Aloe vera) adalah spesies tumbuhan dengan daun berdaging tebal dari genus Aloe.[3] Tumbuhan ini bersifat menahun, berasal dari Jazirah Arab, dan tanaman liarnya telah menyebar ke kawasan beriklim tropis, semi-tropis, dan kering di berbagai belahan dunia.", benefit: "Membantu melancarkan pencernaan, Membantu penyembuhan luka bakar, Membantu menurunkan kadar gula darah"),
    Plant(image: UIImage(named: "kunyit")!, name: "Kunyit", kingdom: "Plantae", division:  "Angiospermae", description: "Kunyit atau kunir, (Curcuma longa Linn. syn. Curcuma domestica Val.), adalah termasuk salah satu tanaman rempah-rempah dan obat asli dari wilayah Asia Tenggara. Tanaman ini kemudian mengalami penyebaran ke daerah Malaysia, Indonesia, Australia bahkan Afrika.", benefit: "Mengobati maag, Meredakan gejala IBS, Mengurangi mual, Meredakan nyeri haid"),
    Plant(image: UIImage(named: "kelapa")!, name: "Kelapa", kingdom: "Plantae", division:  "Commelinids", description: "Kelapa (Cocos nucifera) adalah anggota tunggal dalam marga Cocos dari suku aren-arenan atau Arecaceae. Arti kata kelapa (atau coconut, dalam bahasa Inggris) dapat merujuk pada keseluruhan pohon kelapa, biji, atau buah, yang secara botani adalah pohon berbuah, bukan pohon kacang-kacangan.", benefit: "Mengontrol gula darah, Cocok untuk diet, Meningkatkan kekebalan tubuh,Meningkatkan konsentrasi"),
    Plant(image: UIImage(named: "mengkudu")!, name: "Mengkudu", kingdom: "Plantae", division:  "Angiospermae", description: "Mengkudu (Morinda citrifolia) atau keumeudee (Aceh); pace, kemudu, kudu (Jawa); cangkudu (Sunda); koddhu (Madura); tibah (Bali) berasal daerah Asia Tenggara, tergolong dalam famili Rubiaceae. Nama lain untuk tanaman ini adalah noni (Betawi,Hawaii), nono (Tahiti), nonu (Tonga), ungcoikan (Myanmar) dan ach (Hindi).", benefit: "Mengobati sakit kuning, Anti kanker, Melegakan kembung, Meningkatkan daya tahan tubuh "),
    Plant(image: UIImage(named: "kencur")!, name: "Kencur", kingdom: "Plantae", division:  "Magnoliophyta", description: "Kencur (Kaempferia galanga L.) adalah salah satu jenis empon-empon/tanaman obat yang tergolong dalam suku temu-temuan (Zingiberaceae). Rimpang atau rizoma tanaman ini mengandung minyak atsiri dan alkaloid yang dimanfaatkan sebagai stimulan.", benefit: "Mengobati Masuk angin, Mengobati Batuk dan flu, Mengobati diare "),
    Plant(image: UIImage(named: "kapulaga")!, name: "Kapulaga", kingdom: "Plantae", division:  "Angiospermae", description: "Kapulaga adalah sejenis rempah yang dihasilkan dari biji beberapa tanaman dari genera Elettaria dan Amomum dalam keluarga Zingiberaceae (keluarga jahe-jahean). Kedua genera ini adalah tanaman asli Bangladesh, Bhutan, India, Indonesia, Nepal, dan Pakistan. Di Indonesia, yang umum disebut kapulaga adalah A. compactum itulah; sementara di negara-negara yang berbahasa Inggris yang umum disebut cardamom.", benefit: "Melancarkan sirkulasi darah, Susah buang air besar, Gangguan pencernaan. "),
    Plant(image: UIImage(named: "asam_jawa")!, name: "Asam Jawa", kingdom: "Plantae", division:  "Magnoliophyta", description: "Asam jawa, asam atau asem adalah sejenis buah yang masam rasanya; biasa digunakan sebagai campuran bumbu dalam banyak masakan Indonesia sebagai perasa atau penambah rasa asam dalam makanan, misalnya pada sayur asam atau kadang-kadang pada kuah pempek. Asam juga digunakan untuk campuran jamu tradisional yang dijual oleh penjual jamu.", benefit: " Memperlancar sistem pencernaan, Menjaga kesehatan jantung, Mengelola diabetes, Membantu melindungi organ hati "),
    Plant(image: UIImage(named: "temu_lawak")!, name: "Temu Lawak", kingdom: "Plantae", division: "Magnoliophyta", description: "Temu lawak (Curcuma xanthorrhiza) adalah tumbuhan obat yang tergolong dalam suku temu-temuan (Zingiberaceae)[1]. Ia berasal dari Indonesia, khususnya Pulau Jawa, kemudian menyebar ke beberapa tempat di kawasan wilayah biogeografi Malesia. Saat ini, sebagian besar budidaya temu lawak berada di Indonesia, Malaysia, Thailand, dan Filipina.", benefit: "Mengatasi pegal badan, Anti radang, Obat sakit kuning, Obat masalah perut seperit maag"),
    Plant(image: UIImage(named: "kumis_kucing")!, name: "Kumis Kucing", kingdom: "Plantae", division: "Spermatophyta", description: "Orthosiphon aristatus atau dikenal dengan nama kumis kucing termasuk tanaman dari famili Lamiaceae tau Labiatae Tanaman ini merupakan salah satu tanaman obat asli Indonesia yang mempunyai manfaat dan kegunaan yang cukup banyak dalam menanggulangi berbagai penyakit.", benefit: "Mengobati penyakit-penyakit yang berhubungan dengan organ ginjal, Menyembuhkan diabetes."),
    Plant(image: UIImage(named: "bunga_matahari")!, name: "Bunga Matahari", kingdom: "Plantae", division: "Tracheophyta", description: "Bunga matahari merupakan tumbuhan terna semusim yang berasal dari Amerika Tropik bagian utara (Meksiko), tinggi 3m sampai 5m tergantung varietasnya. Daun tunggal lebar. Batang biasanya ditumbuhi rambut kasar, tegak, jarang bercabang.", benefit: "Membantu mencegah keram otot, Menjaga kesehatan kulit, Mencegah osteoporosis")
    
]

